// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLNETML.Model
{
    public class ModelInput
    {
        [ColumnName("Label"), LoadColumn(0)]
        public float Label { get; set; }


        [ColumnName("Feature"), LoadColumn(1)]
        public string Feature { get; set; }


    }
}
